/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newtodoapp;

import javax.swing.table.DefaultTableModel;

interface Observable {
    public void OnUpdate();
}

/**
 *
 * @author jirim
 */
public class MainFrame extends javax.swing.JFrame implements Observable {    
    Todo todo = new Todo();
    DefaultTableModel modelTable;
    
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        modelTable = (DefaultTableModel) tableTodoList.getModel();
        todo.taskList.registerObservable(this);
        modelTable.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editNewTodo = new javax.swing.JTextField();
        buttonCreateTodo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTodoList = new javax.swing.JTable();
        buttonDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Todo App");

        editNewTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNewTodoActionPerformed(evt);
            }
        });

        buttonCreateTodo.setText("Create");
        buttonCreateTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateTodoActionPerformed(evt);
            }
        });

        tableTodoList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Completed", "Text", "Due"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTodoList);
        if (tableTodoList.getColumnModel().getColumnCount() > 0) {
            tableTodoList.getColumnModel().getColumn(0).setMinWidth(30);
            tableTodoList.getColumnModel().getColumn(0).setPreferredWidth(30);
            tableTodoList.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        buttonDashboard.setText("Dashboard");
        buttonDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editNewTodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateTodo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDashboard)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editNewTodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCreateTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDashboard)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDashboardActionPerformed
        DashboardFrame.main(null);
    }//GEN-LAST:event_buttonDashboardActionPerformed

    private void buttonCreateTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateTodoActionPerformed
        Task task = new Task();
        task.setName(editNewTodo.getText());
        task.setCompleted(false);
                
        todo.taskList.addTask(task);    
        
        editNewTodo.setText("");
    }//GEN-LAST:event_buttonCreateTodoActionPerformed

    private void editNewTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNewTodoActionPerformed
        buttonCreateTodo.doClick();
    }//GEN-LAST:event_editNewTodoActionPerformed

    public void OnUpdate() {
        modelTable.setRowCount(0);
        
        for (int i = 0; i < todo.taskList.getTasksCount(); i++) {
            Task task = todo.taskList.getTask(i);
            
            modelTable.addRow(new Object[] { task.getCompleted(),  task.getName(), " - " });
        }
        //modelTable.addRow( new Object[]{ false, "..", "25/65/2024" } );
    }
    
    
    private static MainFrame instance;
    public static MainFrame getInstance() {
        return instance;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                instance = new MainFrame();
                instance.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateTodo;
    private javax.swing.JButton buttonDashboard;
    private javax.swing.JTextField editNewTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTodoList;
    // End of variables declaration//GEN-END:variables
}
